# For dataprovider
label: "label"
path2data: "dataset"
path2data_test: "test_img"
format_img: "png"
class2label: {"": 0, "" : 1, "" : 2}
label2class: {0 : "", 1 : "", 2 : ""}

# For ImageClassifer
is_train: false
loss: "cross_entropy"
lr: 0.01
batch_size: 10
feature_size: 768
num_epochs: 10
model_name: "models/vgg16.pth"
freeze_layer: -1
writername: "tensorboard_run/test2"
log_item_name: ["train_loss", "accuracy"]

